### ISSUE TITLE
contemporary toolchain issue

### ISSUE THREAD

**Issue by julescarbon** [thenickdude/chickenpaint#1]
Hey there,

Wanted to warn you, when trying to compile this project, I ran into the dreaded `ParseError: ‘import’ and ‘export’ may appear only with ‘sourceType: module’` issue, as detailed here: https://medium.com/@dmitriid/javascript-fatigue-vs-stockholm-syndrome-631d4f524008#.qkbi6afjf - I'm not the only one, my clever friend who pointed out your project to me also had this problem.

I ended up doing the following:

```
for i in `find js -name '*.js' `; do node_modules/.bin/babel $i > resources/$i; done
make resources/css/chickenpaint.css
node_modules/.bin/browserify --standalone ChickenPaint --outfile resources/js/chickenpaint.js -d -e resources/js/ChickenPaint.src.js
```

I was then able to run the tests.  The "less" step worked fine, but there is some issue with `babelify` or possibly `eslint`.  I would suggest trying a dry build of this, or at least second-guessing your toolchain.

Great app, many thanks!  Very glad someone made the conversion.  Going to do some cool stuff with this.

**Comment by thenickdude** [comment]
Which version of Node are you running?

**Comment by thenickdude** [comment]
Apparently there was a problem with the way that the "only" setting was defined in .babelrc, which was causing Babelify to not transform those files. Please check out the newest commit, 76cc38bdd0bb636d6a1a1d978ba115d481da1408, which now builds for me using a brand new clone.
