### ISSUE TITLE
Are there any plans to update the built files?

### ISSUE THREAD

**Issue by satopian** [thenickdude/chickenpaint#19]
Thank you for developing a great app.  
I maintain the PHP program of the OEKAKI board that has existed for a long time.  
I was able to make the bulletin board of the PHP program compatible with Chicken Paint.  
That's because save.php was very helpful.  
The trouble is that I'm new to programming and I'm not familiar with build.  
I installed various things and tried to build.  
However, an error occurs and it does not succeed.  
Thanks to the pre-built files in the release, OEKAKI is now available, but its version was made in 2018.  
Is it possible to get a new version that has been built?  
I can only use the Version of 2018 one in the current state. 

![image](https://user-images.githubusercontent.com/44894014/117584607-dee14900-b148-11eb-9997-bc2d7bfd8486.png)

I only have a Windows environment, so I've tried various installations for compatibility, but I get screen-like errors.
It would be very helpful if you could download the latest or stable new pre-built files. Can you please release a new pre-built file?
Please.

**Comment by thenickdude** [comment]
If you want to build it, the easiest way is to install Ubuntu using Windows Subsystem for Linux, then you can easily install npm, make, etc as needed.

I've published an updated build now!
