### ISSUE TITLE
newMode undefined

### ISSUE THREAD

**Issue by fanfare** [thenickdude/chickenpaint#2]
I acquired a built version of chickenpaint.js using the build instructions specified in [issue 1](https://github.com/thenickdude/chickenpaint/issues/1) and was getting an error when trying to select the non-drawing tools. I'm not quite sure how the mix-up originated.. surely something to do with babel? but anyway I managed to resolve the issue by replacing some variables with their actual value. Perhaps this may be of some use to anyone having the same issue.. 

In the `controller.on("modeChange", function (mode) {}` block.. replace each case variable (e.g. `_ChickenPaint2.default.M_DRAW`) with their respective value (e.g. `3`):

you will wind up with this:

    controller.on("modeChange", function (mode) {
      var newMode;
      switch (mode) {
        case 0:
          newMode = curDrawMode;
          break;

        case 1:
          newMode = floodFillMode;
          break;

        case 6:
          newMode = gradientFillMode;
          break;

        case 2:
          newMode = rectSelectionMode;
          break;

        case 3:
          newMode = moveToolMode;
          break;

        case 4:
          newMode = rotateCanvasMode;
          break;

        case 5:
          newMode = colorPickerMode;
          break;

        case 7:
          newMode = transformMode;
          break;
      }

      modeStack.setUserMode(newMode);
    });

**Comment by thenickdude** [comment]
Please try the latest commit, which should fix the Babel building issue and maybe this one as well!
