### ISSUE TITLE
css stylesheet appears to fail to be loaded

### ISSUE THREAD

**Issue by blurymind** [thenickdude/chickenpaint#21]
After building and running the localhost, i get this with no errors in console
![image](https://user-images.githubusercontent.com/6495061/118173000-f4928f00-b424-11eb-906d-57b8f85eaf6e.png)

**Comment by thenickdude** [comment]
What does the file in resources/css/chickenpaint.css have in it? If it's empty, delete it and run make again.

**Comment by blurymind** [comment]
there is a sass file there, but the index is pointing to css
![image](https://user-images.githubusercontent.com/6495061/118176624-90be9500-b429-11eb-9663-6f0c9182c4e1.png)

**Comment by blurymind** [comment]
this is what I get when building

```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js run build --scripts-prepend-node-path=auto

> chickenpaint@0.1.0 build
> make

node_modules/.bin/sass resources/css/chickenpaint.scss > resources/css/chickenpaint.css
node_modules/.bin/postcss --replace resources/css/chickenpaint.css

Process finished with exit code 0
```

**Comment by blurymind** [comment]
interesting, while intellij doesnt list the file, it does exist and is created

![image](https://user-images.githubusercontent.com/6495061/118177199-40940280-b42a-11eb-9454-a34e47d0fc6e.png)

**Comment by thenickdude** [comment]
Hit the little expand arrow on the .scss file to show the css file (IntelliJ bundles generated files together with their originals)

**Comment by thenickdude** [comment]
Fixed 'make generates empty chickenpaint.css if SCSS isn't installed' in 146ab4792dddaebc8e65da33bf21a171ba78df7d

**Comment by blurymind** [comment]
wow you are fast.

Btw running npm start in a terminal outside of intellij also resolves the issue

**Comment by blurymind** [comment]
I confirm your fix made it work in intellij :+1: thanks for that :)
