### ISSUE TITLE
ChickenPaint Oekaki art

### ISSUE THREAD

**Issue by ElizaChikatta** [thenickdude/chickenpaint#4]
I was drawing for FOUR HOURS on chicken smoothie, but when I pulled up the program again, my art was gone! Is there some way to recover a between save?

**Comment by thenickdude** [comment]
Yes, if you used the Save menu command successfully then that can normally be recovered.

You do have this drawing in your Unfinished Drawings section, is that the one you were asking about?

https://www.chickensmoothie.com/oekaki/image/image.php?id=3329285&size=large&format=jpg&rev=1551997595

**Comment by ElizaChikatta** [comment]
Yes! Unfortunately, it seems like it reverted the drawing to what it was before and I must've accidentally saved it again to remove the work I had beforehand :(

**Comment by ElizaChikatta** [comment]
How do you recover it?

**Comment by thenickdude** [comment]
One moment, I'll take a look at the previous revisions.

**Comment by thenickdude** [comment]
Please try editing that drawing again now!

**Comment by ElizaChikatta** [comment]
It says to me that "Failed to load your drawing layers, please try again later"

**Comment by thenickdude** [comment]
Whoops, please try that again one more time

**Comment by ElizaChikatta** [comment]
Oh my gosh, thank you so much! And thank you for responding so quickly!

**Comment by thenickdude** [comment]
No problem!
