### ISSUE TITLE
The color picker is not displayed correctly and becomes white.

### ISSUE THREAD

**Issue by satopian** [thenickdude/chickenpaint#47]
Several ChickenPaint users on my site have reported that when trying to interact with the ChickenPaint color picker, the squares in the color picker turn white.
The OS is win10, win8.1.
The browser is Chrome. (Chrome ver.105)
Users experiencing this issue use Norton antivirus software.
Judging from the situation, I think it's probably a behavior due to Norton's false detection, but I also reported it.
Also, even if the color display part of the color picker turns white, the operation is possible.
The user can select a color without seeing the color picker.

I also had users test it on the chickenpaint-example.
https://thenicdude.github.io/chickenpaint-example/
The result is the same, The problem that the display of the color picker turns white has been reproduced.

The problem started to occur around August 2022.
Until then, there were no reports of problems.

![image](https://user-images.githubusercontent.com/44894014/190568800-e94c6552-9c32-46e0-93b3-37e6ebb1cb14.png)

**Comment by satopian** [comment]
![image](https://user-images.githubusercontent.com/44894014/193414336-df5cf168-c7af-4e60-aaf0-a2f6e5753657.png)  

I've found the condition that causes the problem.
The OS is Windows 8.1, Windows 10, Windows 11.
Chrome is ver105 or 106.
For example, setting Chrome to the following will prevent the color picker from appearing:

> "Use hardware acceleration when available"  

    

![ChickenPaint_Chrome106_bug](https://user-images.githubusercontent.com/44894014/193414213-0ebc00c3-b889-4f6a-83f6-bf9d10ca0a29.gif)  

This is a GIF animation of the reproduction test.

I've reported it to this repository, but I think it's probably a bug in Google Chrome.
The same Chromium-based browser, Microsoft Edge, does not have this issue.

**Comment by thenickdude** [comment]
It looks like this is due to this Chrome bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=1350157

I can work around this by only using putImageData without doing any other drawing on top of it

**Comment by thenickdude** [comment]
This should be fixed now in 0.4.1!

**Comment by satopian** [comment]
@thenickdude Thank you very much. I tried using v0.4.1.
The issue is now resolved.
