### ISSUE TITLE
Building and running on localhost missing?

### ISSUE THREAD

**Issue by blurymind** [thenickdude/chickenpaint#5]
How does one compile this into a minified js file? Can it run on localhost while being developed?

There is no start or run scripts in package.json

**Comment by blurymind** [comment]
ah I see, the npm install command runs an apple compiler, exclusive to mac.. thats why it didnt compile anything.

Can this install script be updated to work on windows and linux?

**Comment by blurymind** [comment]
Can you add instructions on how to run this in localhost? The readme seems to be lacking them, or anything about compiling on linux and windows. I am kind of interested in contributing to the code, but am not sure yet how to run it in dev mode

**Comment by thenickdude** [comment]
Nothing in there requires macOS, it builds fine for me on Ubuntu. What error are you getting?

I'll update the docs to show how to run a local webserver.

**Comment by blurymind** [comment]
i'm on manjaro. If you run npm install, you dont actually get an error, but nothing has compiled. I get this warning
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
which is actually not an error, but I guess a feature not supported?

I guess its not an error as much as being confused as to how to run it after compiling. The readme says   to run the make command,  but that can be easy to miss. I would suggest adding it to package.json and triggering it when running install.

Then if you like more people to pick and tinker with it, you might want to make this nicer by adding an npm start command to package.json.

Most times thats what people run, npm install then npm start or npm run dev (localhost). A lot of devs would go straight to the package.json file to find their entry points and not find any start script. Then be confused for a bit at first until finding their file in the example folder. 

So when its in example, I guess its not running in localhost with reloading. Does that mean you have to run make every time you make changes, then refresh the browser?
The convention is that rebuilding commands are available in package.json too - so you can do npm run build and that would trigger make to compile it. A common convention is to keep the compiled stuff in a /dist folder, not /example. 

So I guess my suggestions are to make this follow conventions more, so its more intuitive to pick up.

1. add build scripts to package.json (npm run build)
2. Keep build results in /dist and examples can be reserved for something else (example files?)
3. add an npm start script to package.json - so literally running npm start would open the app in your browser
4. a higher hanging fruit would be to add npm run dev which would run it in localhost with hot reloading every time changes are made - but that is not a must if it would take too much effort.


In any case, these are easy to add (1,2,3) and I can make a pr if you think they are a good idea? :)

**Comment by thenickdude** [comment]
I've updated it now to add a start command that pops up a webserver for testing, added calls to `make` on install, and updated the readme.

There's nothing written to /example during build, that's just the example page.

**Comment by blurymind** [comment]
Thank you :) I've give it a spin tonight

**Comment by blurymind** [comment]
closing this issue :D thank you for adding these
