### ISSUE TITLE
suggestion: add a github hosted online demo that doesn't require using an external host and  account registration

### ISSUE THREAD

**Issue by blurymind** [thenickdude/chickenpaint#7]
So the current demo is kind of unacessable for anyone who's not interested in registering an account at any of the boards using it.

A suggestion that I think will really help boost this webapp's popularity is to add the latest builds to a release branch and host it via github's io. Here is an example:
https://yarnspinnertool.github.io/YarnEditor/

I kind of did that with 
https://github.com/YarnSpinnerTool/YarnEditor
it has an package.json command that updates the online demo too (see deploy):
https://github.com/YarnSpinnerTool/YarnEditor/blob/master/package.json#L20
the command deploys it to the gh-pages branch
https://github.com/YarnSpinnerTool/YarnEditor/tree/gh-pages
that branch can be set to be live hosted at the settings section of the repository. That makes it super easy to update it in a single command

and anyone can view the demo in a single click, the link to it is very obvious too - clicking on the screenshot of the app at the readme leads you to it. No need to register an account, confirm your email and so on. You can use the webapp right away, even from your phone

**Comment by thenickdude** [comment]
That's a good idea. It's a little awkward though because I suspect people would like to save and load drawings, and the app was never architected to allow loading a new drawing after the app loads (it only supports loading a drawing during startup). Perhaps I can make it restart itself to load.

**Comment by blurymind** [comment]
that would be a nice feature to add and a must have imo :)

**Comment by blurymind** [comment]
I was wondering if we can get chickenpaint's example hosted right here on github. That way people can be easily using it without having to register at the oekaki boards. That way other devs will be able to try it before diving in

A problem I found with that is that the make scripts are not copying the resulting minified files to the example folder. For gh-pages to work, the compiles css/js needs to be in the same or subfolder of where the index file is

If that is sorted all you would need to do is to add this to packages.json after adding gh-pages to dev dependencies

```
    "predeploy": "make dist", <- makes a dist folderof what is to be deployedto the gh-pages branch
    "deploy": "gh-pages -d dist"
```

**Comment by blurymind** [comment]
Thank you for adding the demo, its a huge improvement. 
The way you have done it however is not automated as I suggested with gh-pages.

Every time you fix something on chickenpaint, you would have to manually update it on the other branch. That means that its very likely that in a while the hosted demo will become outdated from what is on dev
