### ISSUE TITLE
Need help opening a .chi file

### ISSUE THREAD

**Issue by Chiaro-Amos** [thenickdude/chickenpaint#8]
I actually found this resource after trying to find out how to open a .chi file for a friend. She used to use ratemydrawings java draw which saved the file as a .chi file. That led me to find chibipaint and then this resource. 

Honestly, I have no idea how to use this in any way and get it to run. My main goal is to try to view her image and then screenshot it and get her a jpg version or pdf to work on. I know this isn't directly relating to chickenpaint, but is there any way you could help?

**Comment by thenickdude** [comment]
I have a (currently private) tool that can make this conversion for you if you email me the .chi file - n.sherlock@gmail.com

**Comment by Chiaro-Amos** [comment]
Sent you the file. Thanks!
